AWSTemplateFormatVersion: 2010-09-09
Description: IAM group and users in the master AWS account

Parameters:
  UserNameParameter:
    Type: String
    Description: The username of the administrator

Resources:
  AdministratorsGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: Administrators
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  AdministratorUser:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - !Ref AdministratorsGroup
      UserName: !Ref UserNameParameter

